stages :
    - build
    - deploy
build_staging :
    stage: build
    script:
          - source /etc/profile
          - echo "java Build..."
          #- cd projects/star-admin/
          - mvn clean package -U -P product -Dmaven.test.skip=true
          - rsync -av target/star-admin.war webserver@192.168.2.9:~/wa-admin/
          - rsync -av target/star-admin.war webserver@192.168.2.10:~/wa-admin/
          - ssh webserver@192.168.2.9  "source /etc/profile;cd ~/wa-admin;rm -rf bak.webapp && mv -f webapp bak.webapp;unzip star-admin.war -d webapp;./restart.sh"
          - ssh webserver@192.168.2.9  "sleep 1m"
          - ssh webserver@192.168.2.10  "source /etc/profile;cd ~/wa-admin;rm -rf bak.webapp && mv -f webapp bak.webapp;unzip star-admin.war -d webapp;./restart.sh"
    only :
        - aochu-master
    tags :
        - java-shell

#stages :
#    - build
#    - deploy
#build_staging :
#    stage: build
#    script:
#          - source /etc/profile
#          - echo "java Build..."
#          #- cd projects/star-admin/
#          - mvn clean package -U -P product -Dmaven.test.skip=true
#          - md5sum target/star-admin.war |awk '{print $1}' > target/star-admin.war.md5
#          ##- rsync -av target/star-admin.war webserver@192.168.31.236:~/star-admin/
#          ##- ssh webserver@192.168.31.236  "source /etc/profile;cd ~/star-admin;rm -rf bak.webapp && mv -f webapp bak.webapp;unzip star-admin.war -d webapp;./restart.sh"
#    artifacts :
#        paths :
#            - target/star-admin.wa*
#        expire_in : 5 mins
#    only :
#        - master
#    tags :
#        - java-shell
#deploy_fabo :
#    stage : deploy
#    script :
#
#        - pwd
#        - /opt/ci-shell/2.0/to-git --rsync-from=$CI_PROJECT_DIR/target/  --git-repository=online/aiwan.admin.api.com.git  --clean=false
#    only :
#        - master
#    tags :
#        - java-shell