stages :
    - build
    - deploy
build_staging :
    stage: build
    script:
          - source /etc/profile
          - echo "java Build..."
          #- cd projects/wa-admin/
          - mvn clean package -U -P test -Dmaven.test.skip=true
          - rsync -av target/star-admin.war webserver@192.168.2.27:~/wa-admin/
          - ssh webserver@192.168.2.27  "source /etc/profile;cd ~/wa-admin;rm -rf bak.webapp && mv -f webapp bak.webapp;unzip star-admin.war -d webapp;./restart.sh"
    only :
        - dev
    tags :
        - java-shell